const samples=[
["JSON","Structured","mint","Structured objects and arrays.","Format, minify, inspect, or ask AI to restructure it.",'{"customer":"Ada","plan":"pro","active":true,"seats":5}'],
["CSV","Structured","peach","Comma-separated tabular data.","Preview rows, convert, or transform the dataset.","name,role,active\nAda,Engineer,true\nLin,Designer,false"],
["XML","Structured","lav","Well-formed XML documents.","Format, inspect, convert, or transform it.",'<catalog>\n  <book id="bk101"><title>Clip Thinking</title><price>12.95</price></book>\n</catalog>'],
["YAML","Structured","sky","Configuration and structured YAML.","Format, convert, validate, or modify it.","project: clippilot\nenvironment: local\nfeatures:\n  detection: true\n  ai: optional"],
["Base64","Security","yellow","Base64-encoded text payloads.","Decode the value and inspect its contents.","SGVsbG8gZnJvbSBDbGlwUGlsb3Qh"],
["JWT","Security","rose","JSON Web Tokens with readable claims.","Inspect the header and payload. This token is intentionally fake.","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0LXVzZXIiLCJleHAiOjQxMDI0NDQ4MDB9.ZmFrZS1zaWduYXR1cmU"],
["UUID","Security","mint","Universally unique identifiers.","Inspect or validate the identifier.","550e8400-e29b-41d4-a716-446655440000"],
["Regex","Code","peach","Regular expression literals.","Explain, test, simplify, or improve it.","/^[a-z]+\\d+$/i"],
["URL","Web & API","sky","Web addresses with query details.","Open it, clean tracking parameters, or inspect its parts.","https://example.com/pricing?utm_source=newsletter&plan=pro&coupon=TEST"],
["cURL","Web & API","lav","Copy-ready HTTP requests.","Inspect, explain, convert, or improve the request.","curl -X POST https://api.example.com/customers -H \"Content-Type: application/json\" -d '{\"name\":\"Ada\"}'"],
["HTTP Headers","Web & API","yellow","Request and response header blocks.","Inspect, format, or explain the headers.","Content-Type: application/json\nCache-Control: no-cache\nX-Request-ID: test-12345\nAccept-Language: en-US"],
["Email Headers","Web & API","rose","Common email metadata headers.","Summarize routing and message metadata.","From: ada@example.com\nTo: team@example.com\nSubject: ClipPilot test\nDate: Tue, 11 Aug 2026 10:30:00 +0400\nMessage-ID: <test-123@example.com>"],
["GraphQL","Web & API","mint","GraphQL queries and mutations.","Format, explain, optimize, or generate integration code.","query GetCustomer($id: ID!) {\n  customer(id: $id) { id name plan }\n}"],
["SQL","Code","peach","Database queries and statements.","Format, explain, optimize, or rewrite the query.","SELECT customer_id, COUNT(*) AS orders\nFROM orders\nWHERE created_at >= '2026-01-01'\nGROUP BY customer_id\nORDER BY orders DESC;"],
["JavaScript","Code","yellow","JavaScript functions and snippets.","Explain, refactor, debug, or generate tests.","const normalizeCustomer = (customer) => {\n  const name = customer.name.trim();\n  return { ...customer, name };\n};"],
["HTML","Code","rose","HTML documents and elements.","Format, inspect, improve, or transform the markup.","<!doctype html>\n<html lang=\"en\"><body><main><h1>Hello, ClipPilot!</h1></main></body></html>"],
["CSS","Code","sky","Stylesheets with multiple rules.","Format, explain, refactor, or improve the styles.",".card { display: grid; gap: 1rem; }\n.card:hover { transform: translateY(-2px); }"],
["Markdown","Code","lav","Markdown documents with rich structure.","Preview, tidy, summarize, or restructure it.","# Launch checklist\n\n- Test clipboard detection\n- Verify local AI\n\n| Plan | Price |\n| --- | --- |\n| Pro | $5 |"],
["Git Diff","Code","mint","Git patches and code changes.","Summarize, review, or explain the change.","diff --git a/greeting.js b/greeting.js\n--- a/greeting.js\n+++ b/greeting.js\n@@ -1 +1 @@\n-console.log('Hello');\n+console.log('Hello, ClipPilot');"],
["Stack Trace","Operations","peach","Application errors with call frames.","Identify likely causes and suggest a fix.","TypeError: Cannot read properties of undefined\n    at formatCustomer (app.js:42:18)\n    at renderPanel (panel.js:17:5)\n    at main (index.js:8:3)"],
["Log","Operations","yellow","Timestamped application logs.","Summarize events, surface errors, or extract a timeline.","2026-08-11 10:30:01 INFO Server started\n2026-08-11 10:30:04 WARN Slow model response\n2026-08-11 10:30:08 ERROR Request timed out"],
["Cron","Operations","rose","Five-field cron schedules.","Translate the schedule or generate alternatives.","*/15 * * * *"],
["Kubernetes","Infrastructure","sky","Kubernetes resource manifests.","Explain, validate, secure, or improve the manifest.","apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: clippilot-demo\nspec:\n  replicas: 2"],
["Terraform","Infrastructure","lav","Terraform resources and outputs.","Explain, validate, secure, or refactor it.","resource \"aws_s3_bucket\" \"demo\" {\n  bucket = \"clippilot-demo\"\n}\noutput \"bucket_name\" {\n  value = aws_s3_bucket.demo.bucket\n}"],
["Dockerfile","Infrastructure","mint","Container image build instructions.","Explain, optimize, or harden the image build.","FROM node:22-alpine\nWORKDIR /app\nCOPY package.json ./\nRUN npm install --omit=dev\nCOPY . .\nCMD [\"node\", \"server.js\"]"],
["Plain Text","Writing","peach","Everyday notes without a specialist format.","Summarize, rewrite, translate, or use a custom AI action.","Please move our project meeting to tomorrow afternoon and send the updated agenda."]
].map(([type,category,tone,description,expected,sample])=>({type,category,tone,description,expected,sample}));
const grid=document.querySelector("#sampleGrid"),filters=document.querySelector("#sampleFilters"),search=document.querySelector("#sampleSearch"),empty=document.querySelector("#sampleEmpty"),count=document.querySelector("#sampleCount"),toast=document.querySelector("#labToast");let active="All";
const esc=v=>v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const categories=["All",...new Set(samples.map(s=>s.category))];
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="${c===active?"active":""}" data-category="${esc(c)}">${esc(c)}</button>`).join("")}
function render(){const term=search.value.trim().toLowerCase(),visible=samples.filter(s=>(active==="All"||s.category===active)&&Object.values(s).join(" ").toLowerCase().includes(term));count.textContent=visible.length;empty.hidden=!!visible.length;grid.innerHTML=visible.map(s=>{const i=samples.indexOf(s);return `<article class="sample-card ${s.tone}"><header><div><small>${esc(s.category)}</small><h3>${esc(s.type)}</h3></div><i>${String(i+1).padStart(2,"0")}</i></header><p>${esc(s.description)}</p><pre><code>${esc(s.sample)}</code></pre><aside><b>Expected in ClipPilot</b><span>${esc(s.expected)}</span></aside><button data-sample="${i}">Copy ${esc(s.type)} sample</button></article>`}).join("")}
async function copy(value,button){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(value);else{const t=document.createElement("textarea");t.value=value;t.style.cssText="position:fixed;opacity:0";document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}const old=button.textContent;button.textContent="Copied — check ClipPilot";toast.textContent="Sample copied. Watch ClipPilot detect it.";toast.classList.add("show");setTimeout(()=>button.textContent=old,1800);setTimeout(()=>toast.classList.remove("show"),2400)}catch{toast.textContent="Copy was blocked. Select the sample text manually.";toast.classList.add("show")}}
filters.onclick=e=>{const b=e.target.closest("[data-category]");if(!b)return;active=b.dataset.category;renderFilters();render()};search.oninput=render;grid.onclick=e=>{const b=e.target.closest("[data-sample]");if(b)copy(samples[+b.dataset.sample].sample,b)};document.querySelector("[data-copy-custom]").onclick=e=>copy(e.currentTarget.dataset.copyCustom,e.currentTarget);renderFilters();render();
