const features = [
  { icon: "{ }", tone: "lav", title: "Structured data", types: "JSON, CSV, XML, YAML", copy: "Explore trees, validate structure, list paths, flatten objects, infer schemas, convert formats, and generate typed consumers.", chips: ["JSON tree", "Schema", "JSONPaths", "CSV tables", "TypeScript", "YAML"], example: '{ "customer": "Ada", "premium": 500 }\n\n→ Interface, schema, table, mock data…' },
  { icon: "SQL", tone: "rose", title: "Queries and databases", types: "Postgres, MySQL, SQL Server, Oracle, Snowflake", copy: "Format SQL, detect dialect signals, flag risky patterns, parameterize literals, explain joins, and optimize with local AI.", chips: ["Beautify", "Dialects", "Review", "Parameterize", "Indexes"], example: "SELECT * FROM policies WHERE status = 'active'\n\n→ Warning · parameterized query" },
  { icon: "API", tone: "mint", title: "APIs and authentication", types: "cURL, URL, JWT, GraphQL, HTTP headers", copy: "Decode tokens, inspect expiry, remove tracking, convert requests to code, generate SDK functions, and review security headers.", chips: ["JWT claims", "Fetch", "Axios", "Python", "PowerShell"], example: 'curl -H "Authorization: Bearer …" /api\n\n→ Breakdown, SDK function, docs' },
  { icon: "</>", tone: "sky", title: "Code and infrastructure", types: "JavaScript, HTML, CSS, Docker, Kubernetes, Terraform", copy: "Inventory dependencies, extract selectors, inspect containers, and flag dangerous infrastructure settings.", chips: ["Dependencies", "Complexity", "Docker", "Kubernetes", "Terraform"], example: "privileged: true\nimage: api:latest\n\n→ Security warnings" },
  { icon: "!", tone: "peach", title: "Debugging and operations", types: "Stack traces, logs, Git diffs, cron, regex", copy: "Highlight root causes, collapse framework noise, count log levels, summarize patches, and explain schedules.", chips: ["Root cause", "Noise removal", "Errors", "Diff stats", "Cron"], example: "ERROR at PolicyService:42\n\n→ Root frame isolated" },
  { icon: "◇", tone: "yellow", title: "Privacy and security", types: "Secrets, tokens, PII, payment data", copy: "Detect credentials locally, exclude sensitive history, create safe copies, and sanitize remote AI requests.", chips: ["API keys", "Private keys", "IBAN", "Cards", "Email", "Safe copy"], example: "sk-proj-••••••••abcd\n\n→ [REDACTED_AI_API_KEY]" }
];

document.querySelector("#featureAccordion").innerHTML = features.map((feature, index) => `<article class="feature ${index === 0 ? "open" : ""}"><button aria-expanded="${index === 0}"><span class="feature-icon ${feature.tone}">${feature.icon}</span><span><b>${feature.title}</b><small>${feature.types}</small></span><i>+</i></button><div class="panel"><div><h3>Useful immediately.</h3><p>${feature.copy}</p><div class="chips">${feature.chips.map((chip) => `<span>${chip}</span>`).join("")}</div></div><pre>${feature.example}</pre></div></article>`).join("");
document.querySelectorAll(".feature>button").forEach((button) => button.addEventListener("click", () => { const item = button.parentElement; const opening = !item.classList.contains("open"); document.querySelectorAll(".feature").forEach((other) => { other.classList.remove("open"); other.querySelector("button").setAttribute("aria-expanded", "false"); }); if (opening) { item.classList.add("open"); button.setAttribute("aria-expanded", "true"); } }));

document.querySelectorAll(".checkout-link").forEach((link) => { link.href = CLIPPILOT_PRODUCT_CONFIG.CHECKOUT_URL; if (link.href.includes("YOUR-")) link.addEventListener("click", (event) => { event.preventDefault(); alert("Checkout is being configured. Contact support@builtbykris.com for help."); }); });

const comparison = [["Local detection","25+ formats","25+ formats"],["Security scanning","Included","Included"],["JSON","Tree + formatting","Schema, paths, flatten, code"],["SQL","Format + summary","Review, parameterize, AI optimize"],["Ollama","3 actions/day","Unlimited"],["OpenRouter","—","Included"],["History","10 clips","100 clips"],["Search + favorites","Included","Included"],["Collections","—","Included"],["Import/export","—","Included"],["Custom detectors","—","Included"]];
document.querySelector("#comparisonRows").innerHTML = comparison.map((row) => `<tr><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td></tr>`).join("");

